vich_uploader:
    db_driver: orm

    mappings:
        event:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/images/uploads/events'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
